step 1] 데이터 불러서 한 행씩 출력하기

In [1]:
import csv

In [ ]:
file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  print(row)
  #최고기온 데이터만 추출  -> 오류 -> 결측치 때문에
  row[-1] =float(row[-1])  # float(row[4]) 와 같음 -> 최고기온은 마지막 인덱스에 있어서 -1로도 가능하다

file.close()

setp 2] 데이터 중 최고 기온을 실수로 변환하여 한 행씩 출력하기

In [ ]:
import csv

max_temp = -999 #최고 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
max_data = '' #최고 기온이 가장 높았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #최고 기온 데이터가 ''(결측치) 인지 확인
  if row[-1] == '':
    row[-1] = -999 # -999 넣어서 결측치가 있떤 자리라고 표시
    
  row[-1] = float(row[-1])
  print(row[0], row[-1])    #날짜 데이터와 같이 출력

file.close()

step 3] 최고 기온과 최고 기온이었던 날짜 찾기

In [17]:
import csv

max_temp = -999 #최고 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
max_data = '' #최고 기온이 가장 높았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #최고 기온 데이터가 ''(결측치) 인지 확인
  if row[-1] == '':
    row[-1] = -999 # -999 넣어서 결측치가 있떤 자리라고 표시
    
  row[-1] = float(row[-1])
  # print(row[0], row[-1])    #날짜 데이터와 같이 출력

  if max_temp < row[-1]:
    max_date = row[0]
    max_temp = row[-1]

file.close()

print('기상 관측 이래 서울의 최고 기온이 가장 높았던 날은', max_date+'로', max_temp,'도 였습니다.')

기상 관측 이래 서울의 최고 기온이 가장 높았던 날은 2018-08-01로 39.6 도 였습니다.

step 4] 최저 기온과 최저 기온이었던 날짜 찾기

In [26]:
import csv

min_temp = 999 #최저 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
min_date = '' #최저 기온이 가장 낮았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #최고 기온 데이터가 ''(결측치) 인지 확인
  if row[-2] == '':
    row[-2] = 999 # 999 넣어서 결측치가 있떤 자리라고 표시
    
  row[-2] = float(row[-2])
  # print(row[0], row[-2])    #날짜 데이터와 같이 출력

  if min_temp > row[-2]:
    min_date = row[0]
    min_temp = row[-2]

file.close()

print('기상 관측 이래 서울의 최저 기온이 가장 낮았던 날은', min_date+'로', min_temp,'도 였습니다.')

기상 관측 이래 서울의 최저 기온이 가장 낮았던 날은 1927-12-31로 -23.1 도 였습니다.

평균 최저

In [30]:
import csv

mean_temp = 999 #평균 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
mean_date = '' #평균 기온이 가장 낮았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #평균 기온 데이터가 ''(결측치) 인지 확인
  if row[2] == '':
    row[2] = 999 # 999 넣어서 결측치가 있떤 자리라고 표시
    
  row[2] = float(row[2])
  # print(row[0], row[2])    #날짜 데이터와 같이 출력

  if mean_temp > row[2]:
    mean_date = row[0]
    mean_temp = row[2]

file.close()

print('기상 관측 이래 서울의 평균 기온이 가장 낮았던 날은', mean_date+'로', mean_temp,'도 였습니다.')

기상 관측 이래 서울의 평균 기온이 가장 낮았던 날은 1915-01-13로 -19.2 도 였습니다.

평균 최고

In [31]:
import csv

mean_temp = -999 #평균 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
mean_date = '' #평균 기온이 가장 높았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #평균 기온 데이터가 ''(결측치) 인지 확인
  if row[2] == '':
    row[2] = -999 # -999 넣어서 결측치가 있떤 자리라고 표시
    
  row[2] = float(row[2])
  # print(row[0], row[2])    #날짜 데이터와 같이 출력

  if mean_temp < row[2]:
    mean_date = row[0]
    mean_temp = row[2]

file.close()

print('기상 관측 이래 서울의 평균 기온이 가장 높았던 날은', mean_date+'로', mean_temp,'도 였습니다.')

기상 관측 이래 서울의 평균 기온이 가장 높았던 날은 2018-08-02로 33.7 도 였습니다.

In [ ]:
import csv

mean_temp = -999 #평균 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
mean_date = '' #평균 기온이 가장 높았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #평균 기온 데이터가 ''(결측치) 인지 확인
  if row[2] == '':
    row[2] = -999 # -999 넣어서 결측치가 있떤 자리라고 표시
    
  row[2] = float(row[2])
  # print(row[0], row[2])    #날짜 데이터와 같이 출력

  if mean_temp < row[2]:
    mean_date = row[0]
    mean_temp = row[2]

file.close()

print('기상 관측 이래 서울의 평균 기온이 가장 높았던 날은', mean_date+'로', mean_temp,'도 였습니다.')

In [16]:
import csv

max_temp = -999 #최고 기온 값을 저장할 변수 ..명확한 결과를 위해 극적인 값으로 세팅    숫자는 ''없이
max_data = '' #최고 기온이 가장 높았던 날짜를 저장하는 변수      문자는 ''

file = open('/content/seoul.csv', 'r', encoding = 'cp949')

data = csv.reader(file)
header = next(data)

for row in data:
  #최고 기온 데이터가 ''(결측치) 인지 확인
  if row[-1] == '':
    row[-1] = -999 # -999 넣어서 결측치가 있떤 자리라고 표시
    
  row[-1] = float(row[-1])
  # print(row[0], row[-1])    #날짜 데이터와 같이 출력


test = -999
for a in range(len(row)):
  if test < int(row[a+1][-1]):
    test = int(row[a+1][-1])
print(test)

file.close()

TypeError: ignored